### ISSUE TITLE
TODO Functionnalities

### ISSUE THREAD

**Issue by aalaesar** [aalaesar/manage-bind#1]
- [X] Rework tasks structures
- [X] master zone files management
- [x] slave zone files management
- [x] master zone check
- [x] Reworks zone folders : fuse masters and slaves folder
- [x] add support for raw zone files
- [x] rework bind global options
- [x] rework zone statements
- [ ] add clauses
  - [ ] acl
  - [ ] view
  - [ ] lwres
  - [ ] masters (lists)
  - [ ] server
  - [ ] view
  - [ ] trusted-keys
  - [ ] Statistics
  - [ ] logging ?
- [ ] add Wiki
- [x] rework README.md
- [ ] add uninstallation ?

**Comment by aalaesar** [comment]
- [ ] Reworks zone folders : fuse masters and slaves folder
- [ ] add templates for default zones and named.conf
- [ ] add support for raw zone files
